### PR TITLE
Remove HSP profile and add service record for AA profile

### PR DESCRIPTION
**Pull request by Demon000**

### CODE REVIEW

**Comment by hkfuertes** [comment]
If it helps, I made it build (I think) but after Bluetooth pairing, nothing happens...
[patch_nohsp_mine.zip](https://github.com/nisargjhaveri/AAWirelessDongle/files/13439239/patch_nohsp_mine.zip)

**Comment by Demon000** [comment]
> If it helps, I made it build (I think) but after Bluetooth pairing, nothing happens... [patch_nohsp_mine.zip](https://github.com/nisargjhaveri/AAWirelessDongle/files/13439239/patch_nohsp_mine.zip)

I pushed an updated patch. Besides the obvious " inside " issue, I was missing the call to DBus::Variant

**Comment by nisargjhaveri** [comment]
I tried the latest changes as well, doesn't seem to work as is. Do you have a similar setup that works without the HSP handling, we're maybe still missing something?

Two issues I noticed:
1. `Connect` call on RPi fails because it cannot find any matching profile to connect to, though this might not be the actual cause as the phone still gets connected briefly.
2. The phone does not react and does not connect to the AA service on this connection as it does when HSP is connected.

**Comment by gamelaster** [comment]
I can confirm that even when you disable "voice calls" on Bluetooth device configuration page, it will not connect at all. so HSP is needed.

**Pull request closed without merging**
